-- Category: DQL (Data Query Language)
-- Purpose: Aggregation functions after JOIN (COUNT, SUM, AVG, MIN, MAX) with GROUP BY

-- Count the total number of orders placed by each customer.
SELECT
    c.customer_id,
    c.customer_name,
    COUNT(o.order_id) AS total_orders
FROM customers AS c
LEFT JOIN orders AS o
    ON c.customer_id = o.customer_id
GROUP BY c.customer_id, c.customer_name;

-- Calculate total revenue generated by each customer.
SELECT
    c.customer_id,
    c.customer_name,
    SUM(o.quantity * p.price) AS total_revenue
FROM customers AS c
JOIN orders AS o
    ON c.customer_id = o.customer_id
JOIN products AS p
    ON o.product_id = p.product_id
GROUP BY c.customer_id, c.customer_name;

-- Calculate average quantity per product and count its order lines.
SELECT
    p.product_id,
    p.product_name,
    AVG(o.quantity) AS average_quantity,
    COUNT(o.order_id) AS order_count
FROM products AS p
JOIN orders AS o
    ON p.product_id = o.product_id
GROUP BY p.product_id, p.product_name;

-- Summarize revenue by category, including minimum and maximum line revenue.
SELECT
    p.category,
    SUM(o.quantity * p.price) AS category_revenue,
    MIN(o.quantity * p.price) AS minimum_order_revenue,
    MAX(o.quantity * p.price) AS maximum_order_revenue
FROM products AS p
JOIN orders AS o
    ON p.product_id = o.product_id
GROUP BY p.category;
